version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8888:80
      - 4434:443
    volumes:
      - ${BASEPATH}/src/html:/var/www/html/:rw
      - ${BASEPATH}/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${BASEPATH}/nginx/access.log:/etc/nginx/access.log:rw
      - ${BASEPATH}/nginx/error.log:/etc/nginx/error.log:rw
      - ${BASEPATH}/nginx/server.crt:/etc/nginx/ssl/server.crt:rw
      - ${BASEPATH}/nginx/server.key:/etc/nginx/ssl/server.key:rw
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes: 
      - ${BASEPATH}/src/html:/var/www/html/:rw
    ports: 
      - 9000:9000
    networks:
      - laravel
  mysql:
    image: mysql:5.7.26
    container_name: mysql
    user: "1000:50"
    command: --innodb-use-native-aio=0 --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 4648947
      MYSQL_DATABASE: fetchfeeds
    ports:
      - 3308:3306
    volumes:
      - ${BASEPATH}/mysql/my.cnf:/etc/mysql/conf.d/mysql.cnf
      - ${BASEPATH}/mysql/data:/var/lib/mysql:rw
    networks:
      - laravel
  sphinx:
    image: macbre/sphinxsearch:3.0.3
    container_name: sphinx
    ports:
    - 192.168.99.101:9306:9306 # bind to local interface only!
    volumes:
    # - ${BASEPATH}/sphinx/sphinxdata:/opt/sphinx/index  # directory where sphinx will store index data
    - ${BASEPATH}/sphinx/sphinx.conf:/opt/sphinx/conf/sphinx.conf  # SphinxSE configuration file
    # - ${BASEPATH}/sphinx/sphinxdata:/sphinxdata
    - ${BASEPATH}/sphinx/sphinxlog:/sphinxlog
    - ${BASEPATH}/sphinx/sphinxbin:/sphinxbin      
     
